### ISSUE TITLE
Incompatibility with my AuthMod 1.12.2 (Problematic !)

### ISSUE THREAD

**Issue by Aang23** [Thutmose/ThutPerms#13]
No problem when working around default commands or ThutEssentials commands, or even with one of my mods. BUT when using AuthMod (my /login mod), ThutPerms totally disable commands like /login, causing a server-side error. For the permission I have used the exact class name. (com.auth.mod.commands.LoginCommand)
I have allowed bypassing for owners, and it only works if all perms are given.

Still trying to make this work. It work before restarting the server.

> [15:56:49] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.CommandEvent@1024dd47:
java.lang.NullPointerException: null
        at thut.permissions.PermissionsHolder.hasPermission(PermissionsHolder.java:39) ~[PermissionsHolder.class:?]
        at thut.permissions.GroupManager.hasPermission(GroupManager.java:85) ~[GroupManager.class:?]
        at thut.permissions.ThutPerms.canUse(ThutPerms.java:257) ~[ThutPerms.class:?]
        at thut.permissions.ThutPerms.commandUseEvent(ThutPerms.java:136) ~[ThutPerms.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_865_ThutPerms_commandUseEvent_CommandEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:54) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[15:56:49] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[15:56:49] [Server thread/ERROR] [FML]: 0: HIGHEST
[15:56:49] [Server thread/ERROR] [FML]: 1: ASM: com.auth.mod.events.CommandEvents@72680b15 CommandEvents(Lnet/minecraftforge/event/CommandEvent;)V
[15:56:49] [Server thread/ERROR] [FML]: 2: NORMAL
[15:56:49] [Server thread/ERROR] [FML]: 3: ASM: thut.permissions.ThutPerms@55327514 commandUseEvent(Lnet/minecraftforge/event/CommandEvent;)V
[15:56:49] [Server thread/ERROR] [FML]: 4: LOWEST
[15:56:49] [Server thread/ERROR] [FML]: 5: ASM: thut.essentials.commands.chatcontrol.Spy@101d5bb chat(Lnet/minecraftforge/event/CommandEvent;)V
[15:56:49] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at thut.permissions.PermissionsHolder.hasPermission(PermissionsHolder.java:39) ~[PermissionsHolder.class:?]
        at thut.permissions.GroupManager.hasPermission(GroupManager.java:85) ~[GroupManager.class:?]
        at thut.permissions.ThutPerms.canUse(ThutPerms.java:257) ~[ThutPerms.class:?]
        at thut.permissions.ThutPerms.commandUseEvent(ThutPerms.java:136) ~[ThutPerms.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_865_ThutPerms_commandUseEvent_CommandEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:54) ~[bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

PS : It works in 1.11.2...

**Comment by Thutmose** [comment]
this looks like the same thing that I recently fixed in 2.0.4
