### ISSUE TITLE
Error when using commands with mods

### ISSUE THREAD

**Issue by CapturedCherry-zz** [Thutmose/ThutPerms#21]
I upload the mod to my server for Craft Of The Tians 2 and the first time the server start the commands work fine but the second time the server restart I get this.
> [10:01:37] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: help
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744) ~[?:1.8.0_151]
at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481) ~[?:1.8.0_151]
at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:404) ~[?:1.8.0_151]
at java.util.ComparableTimSort.sort(ComparableTimSort.java:213) ~[?:1.8.0_151]
at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_151]
at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_151]
at java.util.ArrayList.sort(ArrayList.java:1460) ~[?:1.8.0_151]
at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_151]
at net.minecraft.command.CommandHelp.func_184900_a(SourceFile:116) ~[cn.class:?]
at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:71) ~[cn.class:?]
at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
For now it only seems to be the help command giving me that error.

**Comment by Thutmose** [comment]
at least one of my commands has something bugged in sorting apparently, I will look into this and fix it.
