### ISSUE TITLE
java.lang.NullPointerException with EnderIO [1.12.2]

### ISSUE THREAD

**Issue by ViRb3** [Thutmose/ThutPerms#26]
Reproducible with many EnderIO blocks in Multi-Player. The easiest one is to take the **Yeta Wrench** and **Shift + Right-Click** an **Endervoir**. The game immediately crashes. Here's a log:

```
java.lang.NullPointerException: Unexpected error
	at thut.permissions.PermissionsManager.hasPermission(PermissionsManager.java:53)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at crazypants.enderio.base.tool.ToolUtil.breakBlockWithTool(ToolUtil.java:41)
	at crazypants.enderio.machines.machine.reservoir.BlockReservoir.func_180639_a(BlockReservoir.java:170)
	at crazypants.enderio.base.item.yetawrench.ItemYetaWrench.onItemUseFirst(ItemYetaWrench.java:102)
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:409)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

### Versions:

EnderCore-1.12.2-0.5.35.jar
EnderIO-1.12.2-5.0.29.jar

**Comment by ViRb3** [comment]
Happens only when the client **and** server have ThutPerms - removing the plugin from the client solved the problem. Feel free to close this issue if this is expected behavior.

**Comment by Thutmose** [comment]
This mod shouldn't ever be run on the client, I will see about finding why it is being run and fixing that
