### ISSUE TITLE
java.lang.NullPointerException with Sampler [1.12.2] [Client]

### ISSUE THREAD

**Issue by ViRb3** [Thutmose/ThutPerms#28]
Possibly similar to #26, ThutPerms is still loaded on the client even in newest version **2.1.3**.

### Reproduce
Installed Sampler and executed the `/csampler` command. ThutPerms crashed and prevented the command from running.

### Log
```
Command 'csampler' threw an exception:
java.lang.NullPointerException
	at thut.permissions.PermissionsManager.commandUseEvent(PermissionsManager.java:112)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1453_PermissionsManager_commandUseEvent_CommandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ClientCommandHandler.executeCommand(ClientCommandHandler.java:86)
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:422)
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:411)
	at net.minecraft.client.gui.GuiChat.keyTyped(SourceFile:81)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3937)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by prjohns** [comment]
Ahh, I see, this is being executed in a slighly different place from the last one, I can get it also fixed for the next release

**Comment by Thutmose** [comment]
I can have this fixed for next release, it is a different location causing this from #26, so I seem to have missed it.

**Comment by ViRb3** [comment]
Just curious, wouldn't it be better if you disable the plugin globally instead of per-hook?

**Comment by Thutmose** [comment]
I would have done that, but I left it this way incase a modpack wanted to try to use permissions for things like unlocking features of things.

I can see about adding a config for disabling it entirely on clients though

**Comment by Thutmose** [comment]
If I do add that config, I will have it to disable on clients by default
