### ISSUE TITLE
Error when typing groupinfo

### ISSUE THREAD

**Issue by ghost** [Thutmose/ThutPerms#32]
When typing just groupInfo I get an error:
[22:05:02] [Server thread/INFO] [minecraft/DedicatedServer]: An unknown error occurred while attempting to perform this command
[22:05:02] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: groupinfo
java.lang.ArrayIndexOutOfBoundsException: 0
        at thut.permissions.commands.GroupInfo.func_184881_a(GroupInfo.java:45) ~[GroupInfo.class:?]
        at thut.permissions.util.CommandWrapper.func_184881_a(CommandWrapper.java:34) ~[CommandWrapper.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Thutmose** [comment]
did you do /groupinfo without arguments?
