### ISSUE TITLE
Worldedit and Thutperms compatibility

### ISSUE THREAD

**Issue by manzipan** [Thutmose/ThutPerms#54]
hello there any chance of getting this fixed with worldedit i realy need a permission mod for my forge server to give users the acsess to world edit if need any details i can provide

**Comment by manzipan** [comment]
[13:32:32] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class ovh.corail.tombstone.event.EventHandler onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		2: NORMAL
		3: ASM: com.mcwbridges.kikoz.MacawsBridges@5d9a036b onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		4: ASM: com.kwpugh.greater_eye.GreaterEye@7e406d0f onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		5: ASM: class mcp.mobius.waila.forge.ForgeWaila$Subscriber serverStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$3859/0x00000008015e56f0@502b042e
		7: net.minecraftforge.eventbus.EventBus$$Lambda$3859/0x00000008015e56f0@313d1d91
		8: LOWEST
		9: ASM: thut.perms.Perms@28b6e5a serverStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractCollection.add(AbstractCollection.java:251)
	at TRANSFORMER/worldedit@7.3.0-SNAPSHOT+6046-757bef1/com.sk89q.worldedit.forge.ForgePlayer.<init>(ForgePlayer.java:76)
	at TRANSFORMER/worldedit@7.3.0-SNAPSHOT+6046-757bef1/com.sk89q.worldedit.forge.ForgeAdapter.adaptPlayer(ForgeAdapter.java:248)
	at TRANSFORMER/worldedit@7.3.0-SNAPSHOT+6046-757bef1/com.sk89q.worldedit.forge.CommandWrapper.lambda$requirementsFor$2(CommandWrapper.java:84)
	at TRANSFORMER/thutperms@5.0.3/thut.perms.management.PermissionsManager.wrap(PermissionsManager.java:139)
	at TRANSFORMER/thutperms@5.0.3/thut.perms.management.PermissionsManager.wrap(PermissionsManager.java:181)
	at TRANSFORMER/thutperms@5.0.3/thut.perms.management.PermissionsManager.wrapCommands(PermissionsManager.java:195)
	at TRANSFORMER/thutperms@5.0.3/thut.perms.management.PermissionsManager.wrapCommands(PermissionsManager.java:92)
	at TRANSFORMER/thutperms@5.0.3/thut.perms.Perms.serverStarting(Perms.java:110)
	at net.minecraftforge.eventbus.ASMEventHandler_40_Perms_serverStarting_ServerStartingEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.19/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:102)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:209)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

[13:32:32] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:251) ~[?:?]
	at com.sk89q.worldedit.forge.ForgePlayer.<init>(ForgePlayer.java:76) ~[worldedit-forge-mc1.18.1-7.3.0-SNAPSHOT-dist.jar%2373!:7.3.0-SNAPSHOT]
	at com.sk89q.worldedit.forge.ForgeAdapter.adaptPlayer(ForgeAdapter.java:248) ~[worldedit-forge-mc1.18.1-7.3.0-SNAPSHOT-dist.jar%2373!:7.3.0-SNAPSHOT]
	at com.sk89q.worldedit.forge.CommandWrapper.lambda$requirementsFor$2(CommandWrapper.java:84) ~[worldedit-forge-mc1.18.1-7.3.0-SNAPSHOT-dist.jar%2373!:7.3.0-SNAPSHOT]
	at thut.perms.management.PermissionsManager.wrap(PermissionsManager.java:139) ~[thutperms-1.18.1-5.0.3.jar%2367!:5.0.3]
	at thut.perms.management.PermissionsManager.wrap(PermissionsManager.java:181) ~[thutperms-1.18.1-5.0.3.jar%2367!:5.0.3]
	at thut.perms.management.PermissionsManager.wrapCommands(PermissionsManager.java:195) ~[thutperms-1.18.1-5.0.3.jar%2367!:5.0.3]
	at thut.perms.management.PermissionsManager.wrapCommands(PermissionsManager.java:92) ~[thutperms-1.18.1-5.0.3.jar%2367!:5.0.3]
	at thut.perms.Perms.serverStarting(Perms.java:110) ~[thutperms-1.18.1-5.0.3.jar%2367!:5.0.3]
	at net.minecraftforge.eventbus.ASMEventHandler_40_Perms_serverStarting_ServerStartingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:102) ~[forge-1.18.1-39.0.19-universal.jar%2382!:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:209) ~[server-1.18.1-20211210.034407-srg.jar%2378!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644) ~[server-1.18.1-20211210.034407-srg.jar%2378!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2378!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Thutmose** [comment]
does worldedit use forge permissions api?

The particular log you have posted there seems to indicate it is a problem in worldedit when thutperms tries to determine the default perms required for the command, `com.sk89q.worldedit.forge.ForgePlayer.(ForgePlayer.java:76)` is erroring when it tries to do something to the fakeplayer used to test the command
